package com.reddy.vittify.presentation.ui.features.settings.about

import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.Gavel
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.input.nestedscroll.nestedScroll
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.reddy.vittify.R
import com.reddy.vittify.presentation.effects.overScrollVertical
import com.reddy.vittify.presentation.effects.rememberOverscrollFlingBehavior
import com.reddy.vittify.presentation.ui.components.CustomTitleTopAppBar
import com.reddy.vittify.presentation.ui.features.categories.NavigationContent
import com.reddy.vittify.presentation.ui.theme.*
import dev.chrisbanes.haze.HazeState
import dev.chrisbanes.haze.hazeSource

data class TermsSection(
    val title: String,
    val paragraphs: List<String>
)

private val TERMS_SECTIONS = listOf(
    TermsSection(
        title = "1. Acceptance of Terms",
        paragraphs = listOf(
            "By installing, accessing, or using Vittify, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application."
        )
    ),
    TermsSection(
        title = "2. Nature of the Application & Financial Disclaimer",
        paragraphs = listOf(
            "Vittify is an on-device personal expense tracker and organizational tool designed to help you monitor personal spending.",
            "Vittify does NOT provide certified financial advice, legal counsel, tax planning, investment recommendations, or banking services.",
            "Information displayed within the app—including currency exchange rates, budget projections, and spending totals—is provided for convenience and estimation purposes only. Always refer to your official bank statements for authoritative balances."
        )
    ),
    TermsSection(
        title = "3. Currency Exchange Rates Notice & Disclaimer",
        paragraphs = listOf(
            "The exchange rates displayed within this app are for informational purposes only and should not be used for investment decisions. These rates are estimates and may not reflect actual rates.",
            "By using this app, you acknowledge that you understand and accept these limitations and that you assume full responsibility for any decisions made based on the information provided within the app."
        )
    ),
    TermsSection(
        title = "4. SMS Parsing & Data Verification",
        paragraphs = listOf(
            "Automatic transaction detection relies on parsing incoming SMS alerts sent by financial institutions. While our parsing algorithms are regularly tested and refined, format variations and network anomalies can occasionally result in misparsed or missed transactions.",
            "You are solely responsible for reviewing, verifying, and adjusting transactions, category assignments, and account balances generated by the app."
        )
    ),
    TermsSection(
        title = "5. User Security Responsibilities",
        paragraphs = listOf(
            "Because Vittify operates with a local-first, serverless architecture, you are responsible for maintaining the physical and digital security of your device.",
            "If you configure encrypted cloud backups or WebDAV sync, you are solely responsible for safeguarding your encryption passphrase. Vittify cannot recover lost passphrases or decrypt backups without the secret key.",
            "We strongly recommend enabling App Lock (Biometrics or PIN) within the app to guard against unauthorized physical access."
        )
    ),
    TermsSection(
        title = "6. Third-Party Services & Webhooks",
        paragraphs = listOf(
            "If you utilize optional third-party integrations—such as Google Drive for cloud backups, private WebDAV endpoints, or custom outgoing Webhooks—your use of those services is subject to their respective terms and privacy policies.",
            "Vittify is not responsible for the availability, security, or data handling practices of third-party storage or automation providers."
        )
    ),
    TermsSection(
        title = "7. Open Source Software & Modifications",
        paragraphs = listOf(
            "Vittify is open-source software. You are free to inspect, fork, or modify the source code under the applicable open-source license.",
            "Any custom builds or modifications created by third parties are not the responsibility of the official Vittify project maintainers."
        )
    ),
    TermsSection(
        title = "8. Warranty Disclaimer & Limitation of Liability",
        paragraphs = listOf(
            "Vittify is provided on an 'AS IS' and 'AS AVAILABLE' basis, without warranty of any kind, express or implied.",
            "To the maximum extent permitted by applicable law, the authors, maintainers, and contributors shall not be held liable for any direct, indirect, incidental, or consequential damages resulting from the use of or inability to use this software, including data loss, hardware failure, or financial decisions made based on app estimations."
        )
    )
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TermsOfServiceScreen(
    onNavigateBack: () -> Unit
) {
    val scrollBehavior = TopAppBarDefaults.exitUntilCollapsedScrollBehavior()
    val scrollBehaviorSmall = TopAppBarDefaults.pinnedScrollBehavior()
    val hazeState = remember { HazeState() }

    Scaffold(
        modifier = Modifier.nestedScroll(scrollBehavior.nestedScrollConnection),
        containerColor = MaterialTheme.colorScheme.background,
        topBar = {
            CustomTitleTopAppBar(
                title = stringResource(R.string.terms_of_service),
                scrollBehaviorSmall = scrollBehaviorSmall,
                scrollBehaviorLarge = scrollBehavior,
                hazeState = hazeState,
                hasBackButton = true,
                navigationContent = { NavigationContent(onNavigateBack) }
            )
        }
    ) { paddingValues ->
        val listState = rememberLazyListState()

        LazyColumn(
            state = listState,
            modifier = Modifier
                .fillMaxSize()
                .hazeSource(state = hazeState)
                .overScrollVertical()
                .padding(
                    start = Dimensions.Padding.content,
                    end = Dimensions.Padding.content,
                    top = paddingValues.calculateTopPadding(),
                    bottom = 24.dp
                ),
            flingBehavior = rememberOverscrollFlingBehavior { listState },
            verticalArrangement = Arrangement.spacedBy(Spacing.md)
        ) {
            // Header summary
            item(key = "terms_header") {
                Surface(
                    shape = VittifyShapes.hero,
                    color = MaterialTheme.colorScheme.surfaceContainerHigh,
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(
                        modifier = Modifier.padding(Spacing.lg),
                        verticalArrangement = Arrangement.spacedBy(Spacing.xs)
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(Spacing.sm)
                        ) {
                            Icon(
                                imageVector = Icons.Rounded.Gavel,
                                contentDescription = null,
                                tint = MaterialTheme.colorScheme.primary,
                                modifier = Modifier.size(24.dp)
                            )
                            Text(
                                text = "Terms of Service",
                                style = MaterialTheme.typography.titleMedium,
                                fontWeight = FontWeight.Bold,
                                color = MaterialTheme.colorScheme.onSurface
                            )
                        }

                        Text(
                            text = "Please read these terms carefully. Vittify is an open-source, local-first expense tracker provided free of charge for personal use.",
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            lineHeight = 22.sp
                        )

                        Text(
                            text = "Effective: September 2026",
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.7f),
                            modifier = Modifier.padding(top = 4.dp)
                        )
                    }
                }
            }

            // Terms Sections
            items(TERMS_SECTIONS, key = { it.title }) { section ->
                Surface(
                    shape = VittifyShapes.platter,
                    color = MaterialTheme.colorScheme.surfaceContainer,
                    modifier = Modifier
                        .fillMaxWidth()
                        .border(
                            width = 1.dp,
                            color = MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.2f),
                            shape = VittifyShapes.platter
                        )
                ) {
                    Column(
                        modifier = Modifier.padding(Spacing.lg),
                        verticalArrangement = Arrangement.spacedBy(Spacing.sm)
                    ) {
                        Text(
                            text = section.title,
                            style = MaterialTheme.typography.titleSmall,
                            fontWeight = FontWeight.Bold,
                            color = MaterialTheme.colorScheme.onSurface
                        )

                        HorizontalDivider(
                            color = MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.2f),
                            modifier = Modifier.padding(vertical = 4.dp)
                        )

                        section.paragraphs.forEach { paragraph ->
                            Text(
                                text = paragraph,
                                style = MaterialTheme.typography.bodyMedium,
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                                lineHeight = 22.sp
                            )
                        }
                    }
                }
            }

            // Footer
            item(key = "terms_footer") {
                Text(
                    text = "For inquiries regarding terms or licensing, contact thegodscode@gmail.com.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.7f),
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = Spacing.md)
                )
            }
        }
    }
}

